### ISSUE TITLE
Sending metadata (like headers) inside body as part of the form data should be optional

### ISSUE THREAD

**Issue by mohamnag** [matiasgagliano/bifrost#2]
There are some situations where the server side implementation is not capable of handling additional data sent as part of form or it may cause a major complexity to adopt them. 
Current state of this plugin adds some of the HTTP headers as part of form data, this behaviour if not disabled per default, shall be at least configurable.

**Comment by mohamnag** [comment]
this issue references #1 which was closed in favour of further discussions here.

**Comment by matiasgali** [comment]
Let's say you actually need the extra headers as metadata, what would you need to allow them in AWS signature V4 POST requests? Allowing to set custom metadata would be enought?

**Comment by matiasgali** [comment]
@mohamnag that last commit should be enough to solve the issue. 

Please checkout the new section in the README and try it out. 

Reopen the issue if there's something off.

**Comment by mohamnag** [comment]
@matiasgagliano it seems good enough to fix my problem, I will test it and in case the problem persists will reopen this ticket here. thanks.

by the way, why don't you publish this in bower?

**Comment by matiasgali** [comment]
Published to Bower.
